### ISSUE TITLE
Switch static asset hosting to Cloudflare Pages

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#244]
As discussed today on the call, we want to decouple hosting at `inbrowser.tld` from public gateway infra to make debugging easier by removing factors unrelated to this client-side project.

I will be executing below this week.

## TODO

- [x] Set up Cloudflare Pages build for production and staging
  - [x] `production` branch builds and deploys to https://ipfs-service-worker-gateway.pages.dev
  - [x] `staging` branch builds and deploys to https://staging.ipfs-service-worker-gateway.pages.dev  
- [x] Update Nginx in waterworks-infra to proxy to above domains, instead of rainbows
  - [x] https://github.com/ipshipyard/waterworks-infra/pull/133
    -  [x] [CI error](https://github.com/ipshipyard/waterworks-infra/actions/runs/8991747455/job/24702589763) (resolved)
  - [x]  Cloudflare setup for wildcard certs on `*.ip[fn]s.inbrowser.tld`
  - [x] confirm `_redirects` works as expected
  - [x] confirm `inbrowser.link` backed by https://ipfs-service-worker-gateway.pages.dev
    - [x] subdomain nginx config working as expected
  - [x] confirm `inbrowser.dev` backed by https://staging.ipfs-service-worker-gateway.pages.dev 
    - [x] subdomain nginx config working as expected
- [x] Update CI 
  - [x] remove dance related to CID and dnslink-driven deployments
  - [x] stop updating DNSLinks on main and release
  - [x] make it update `_dnslink.cid.inbrowser.tld` instead of main domain (removes problem with ipfs-companion and brave performing unnecessary redirect)
  - [x] remove cron trigger from smoke test job (no longer need to run every hour)
  - [x] confirm `main` build no longer deploys anything to DNS
- [x] README / docs/dev: document deployment requires push to `staging` or `production`
  
cc @SgtPooki @2color for visibility
